### PR TITLE
feat: Make <esc> and go back to the entry list

### LINKED ISSUE #7: Wishlist - add key to go back from OTP to list
Hello,
thanks for this helpful program. For me it would be helpful to have the possibility to go back from displaying the OTP to the list to select a new account / token.

Current implementation (as i understand) is just a one-shot: start app -> enter password -> select one account -> exit

Here (for being lazy and not wanting to enter my password again and again but being too paranoid to store it on disc / inside env-var) it would be helpful to be able to go back from the OTP to the account list by pressing ESC / arrow left / Q or similar. Now i could select another account and display the OTP there too without having to enter my password again.

Thanks,
Stefan

### PR DESCRIPTION
**Pull request by Granddave**
Go back and exit application with `<esc>`.

`<ctrl+c>` will unfortunately not close the application gracefully
anymore in the code generation view. Works in Zsh, but not in Bash...

Needs to be fixed.

Fixes https://github.com/Granddave/aegis-rs/issues/7

### CODE REVIEW

**Comment by Granddave** [comment]
@sseide @pepa65, Let's continue here.

I managed to fix some of the issues discussed in #7:
- The IO error in the entry selection is fixed by handling the error case
- It's now possible to go back using `<esc>` from the code view, and if `<esc>` is pressed again in the selection view the application is exited. `<q>` was not a simple fix due to the fuzzy finding library used unfortunately, so I went with `<esc>` for both views.
- `<ctrl+c>` is fixed in the selection view, but the code view is still buggy in Bash it seems like. To fix the broken prompt, blindly execute `reset`. Zsh does not have this problem.

**Comment by sseide** [comment]
this new commit acf90b2 seems to work quite well in Bash - `ESC` and `Ctrl-C` work all the time for me.
 - select TOTP and ESC ESC exit fine, Bash worknig
 - select TOTP and Ctrl-C - no error message, Bash works as expected
 - view account list and Ctrl-C - exit and Bash fine.

Maybe some race condition its not working for you? Just tested here without problem.

Only minor new issue now - i cannot select the current TOTP with mouse double click anymore. Its deselected instantly (due to update of seconds left i guess). And not stored inside the X Window clipbord to insert it in other apps with middle mouse key.
This was working with latests official release. From time to time I needed it because the TOTP was not copied into the clipboard right after selecting an account. And it was to long to wait until next token is generated and copied again into the clipboard...

**Comment by pepa65** [comment]
With this commit, when I do Ctrl-C on the TOTP display, it comes back with a cursor, but no echo: nothing gets displayed. (Fixed by `stty sane`.)

If you remove the `exit(0)` from `set_sigint_hook` in `src/main.rs`, it works (in that on the TOTP display, Ctrl-C does nothing).

I think in the modules that are used for the TOTP display, something must happen that doesn't get fixed with a `show_cursor`...

This happens in different terminals: MATE terminal, Sakura, Kitty. It happens with bash and dash.

**Comment by sseide** [comment]
yes - it really seems to be terminal dependent...

* My first test where with *bash + xfce4-terminal*: everything working fine here.
* Using *bash + Yakuake* terminal output is not displayed on TOTP display and Ctrl-C... and starting Aegis again i cannot enter password (or get past the password input question).
* *bash + Konsole* (from KDE) - same as Yakuake

Calling `reset`on Yakuake and Konsole is needed get output again.

**Comment by sseide** [comment]
just a short note after using this version since release:
It integrates wonderful in my daily work, only using ESC to navigate (feels more naturally) and I do not need Ctrl-C, therefor I am not being hit by the console reset bug.

thanks a lot!

**Comment by Granddave** [comment]
Hi again, thanks for your patience and that's good to hear!
If it seems to work good enough with the changes in this PR I'm gonna merge it to make it available to other users as well. :)

**Pull request merged**
